server:
  port: 8080
  contextPath: /eventmanager
---
spring:
  profiles: test,local,default
datasource:
    url: jdbc:h2:~/event_manager_test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
    url: jdbc:mysql://localhost:3306/event_manager
    username: event_manager_admin
    password: qwer1234
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect